services:
  pulso-api-nestjs:
    image: pulso-api-nestjs:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - PULSO_NEST_MYSQL_CONNECTION=
      - NODE_ENV=